### ISSUE TITLE
FOV to Focal Length conversion

### ISSUE THREAD

**Issue by azsry** [HitmanVere/weapon-port-infopedia#1]
BO3 uses focal lengths to manage ADS zoom levels, and should be converted accordingly.

The formula to convert a FOV to its corresponding rectilinear focal length (and vice versa) is as follows (for C++):

```cpp
#define _USE_MATH_DEFINES
#include <cmath>
#include <string>

constexpr double x = 43.266615300557; // Diagonal measurement for a 'normal' 35mm lens

double fov_to_length( double fov ) {
	if ( fov < 1 || fov > 179 )
		return NULL;
	return ( x / ( 2 * tan( M_PI * fov / 360.f ) ) );
}

double length_to_fov( double length, double crop = 1.f ) {
	if ( length < 1 )
		return NULL;

	length *= crop;

	return ( 2 * atan( x / ( 2.f * length ) ) * 180.f / M_PI );
}
```

The crop factor refers to cropping that occurs when using a larger lens and scaling it back to a 35mm equivalent, but since virtual cameras don't behave exactly like real cameras that are limited by the size of their film plane, we don't have to worry about tweaking this value. It's only there for future-proofing.

**Comment by HitmanVere** [comment]
Taking a look at this more when I have time. Both options can be added under Calculations tab, I just need to write the func in C# as that is what we used for coding the program

**Comment by HitmanVere** [comment]
Added both options under Calculate-dropdown menu. FOV -> Focal Length is rounded up four digits while FL -> FOV stays as int https://i.imgur.com/qx9TaxN.png
